installer:
  release: "v0.4.0"
  image: "quay.io/devtron/inception"
  tag: "acb623ff-185-7117"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:933b88b6-7-116"
  devtron:
    image: "quay.io/devtron/hyperion:933b88b6-7-115"
  argocdDexServer:
    image: "quay.io/dexidp/dex:v2.25.0"
  kubelink:
    image: "quay.io/devtron/kubelink:1be465ec-318-7966"
  postgres:
    image: "quay.io/devtron/postgres:11.3.0-debian-9-r28"
  
  migrator:
    image: "quay.io/devtron/migrator:6687f572-133-2208"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "933b88b66045b710140d1c215343ce91a5b7e320"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "933b88b66045b710140d1c215343ce91a5b7e320"
