installer:
  release: "v0.4.0"
  image: "quay.io/devtron/inception"
  tag: "acb623ff-185-7117"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:384cdd21-325-8278"
  devtron:
    image: "quay.io/devtron/hyperion:a5f55594-280-8271"
  argocdDexServer:
    image: "quay.io/dexidp/dex:v2.25.0"
  kubelink:
    image: "quay.io/devtron/kubelink:bb988d66-7-120"
  postgres:
    image: "quay.io/devtron/postgres:11.3.0-debian-9-r28"
  
  migrator:
    image: "quay.io/devtron/migrator:6687f572-133-2208"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "bb988d66653cd9ffc0bb99f41efada2d17dcb8b4"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "bb988d66653cd9ffc0bb99f41efada2d17dcb8b4"
