installer:
  release: v0.4.1
  image: "quay.io/devtron/inception"
  tag: "acb623ff-185-7117"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:89b1a1ab-240-8587"
  devtron:
    image: "quay.io/devtron/hyperion:11d3bc2c-282-8589"
  argocdDexServer:
    image: "quay.io/dexidp/dex:v2.25.0"
  kubelink:
    image: "quay.io/devtron/kubelink:dbb856dd-7-136"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
  
  migrator:
    image: "quay.io/devtron/migrator:6687f572-133-2208"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "dbb856dd387a073913cf518f18511693eb2b986a"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "dbb856dd387a073913cf518f18511693eb2b986a"
